// app/assets/javascripts/components/brand.jsx
import { html } from 'htm/react';
import React, { useState, useRef } from 'react';

const Brand = ({ brand, handleDeleteBrand, handleEditBrand }) => {
  const [edit, setEdit] = useState(false);
  const codeRef = useRef(null);
  const descriptionRef = useRef(null);

  const handleToggle = (e) => {
    e.preventDefault();
    setEdit(!edit);
  };

  const handleDelete = (e) => {
    if (confirm("Are you sure?")) {
      e.preventDefault();
      $.ajaxSetup({
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        }
      });
      $.ajax({
        method: 'DELETE',
        url: `/brands/${brand.id}`,
        dataType: 'JSON',
        success: () => {
          handleDeleteBrand(brand);
        }
      });
    }
  };

  const handleEdit = (e) => {
    e.preventDefault();
    const data = {
      code: codeRef.current.value,
      description: descriptionRef.current.value
    };
    $.ajaxSetup({
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      }
    });
    $.ajax({
      method: 'PUT',
      url: `/brands/${brand.id}`,
      dataType: 'JSON',
      data: { brand: data },
      success: (updatedBrand) => {
        setEdit(false);
        handleEditBrand(brand, updatedBrand);
      }
    });
  };

  const brandRow = () => html`
    <tr>
      <td>
        <a href=${`/brands/${brand.id}`}>${brand.code}</a>
      </td>
      <td>${brand.description}</td>
      <td>
        <button className="btn btn-mini" onClick=${handleToggle}>Edit</button>
        {' '}
        <button className="btn btn-mini btn-danger" onClick=${handleDelete}>Destroy</button>
      </td>
    </tr>
  `;

  const brandForm = () => html`
    <tr>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue=${brand.code}
          ref=${codeRef}
        />
      </td>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue=${brand.description}
          ref=${descriptionRef}
        />
      </td>
      <td>
        <button className="btn btn-mini btn-default" onClick=${handleEdit}>Update</button>
        <button className="btn btn-mini btn-danger" onClick=${handleToggle}>Cancel</button>
      </td>
    </tr>
  `;

  return edit ? brandForm() : brandRow();
};

export default Brand;

// app/assets/javascripts/components/Brand.vue
<template>
  <tr v-if="edit">
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.code"
      />
    </td>
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.description"
      />
    </td>
    <td>
      <button
        class="btn btn-mini btn-default"
        @click="handleEdit"
      >
        Update
      </button>
      <button
        class="btn btn-mini btn-danger"
        @click="toggleEdit"
      >
        Cancel
      </button>
    </td>
  </tr>
  <tr v-else>
    <td>
      <a :href="`/brands/${brand.id}`">{{ brand.code }}</a>
    </td>
    <td>{{ brand.description }}</td>
    <td>
      <button
        class="btn btn-mini"
        @click="toggleEdit"
      >
        Edit
      </button>
      <button
        class="btn btn-mini btn-danger"
        @click="handleDelete"
      >
        Destroy
      </button>
    </td>
  </tr>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'Brand',
  props: {
    brand: Object,
    handleDeleteBrand: Function,
    handleEditBrand: Function,
  },
  setup(props) {
    const edit = ref(false);
    const form = ref({
      code: props.brand.code,
      description: props.brand.description,
    });

    const toggleEdit = () => {
      edit.value = !edit.value;
    };

    const handleDelete = async () => {
      if (confirm('Are you sure?')) {
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        const response = await fetch(`/brands/${props.brand.id}`, {
          method: 'DELETE',
          headers: {
            'X-CSRF-Token': csrfToken,
          },
        });

        if (response.ok) {
          props.handleDeleteBrand(props.brand);
        }
      }
    };

    const handleEdit = async () => {
      const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
      const response = await fetch(`/brands/${props.brand.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': csrfToken,
        },
        body: JSON.stringify({ brand: form.value }),
      });

      if (response.ok) {
        const data = await response.json();
        props.handleEditBrand(props.brand, data);
        edit.value = false;
      }
    };

    return {
      edit,
      form,
      toggleEdit,
      handleDelete,
      handleEdit,
    };
  },
};
</script>
