// app/assets/javascripts/components/Category.vue
<template>
  <tr v-if="edit">
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.code"
      />
    </td>
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.description"
      />
    </td>
    <td>
      <button
        class="btn btn-mini btn-default"
        @click="handleEdit"
      >
        Update
      </button>
      <button
        class="btn btn-mini btn-danger"
        @click="toggleEdit"
      >
        Cancel
      </button>
    </td>
  </tr>
  <tr v-else>
    <td>
      <a :href="`/categories/${category.id}`">{{ category.code }}</a>
    </td>
    <td>{{ category.description }}</td>
    <td>
      <button
        class="btn btn-mini"
        @click="toggleEdit"
      >
        Edit
      </button>
      <button
        class="btn btn-mini btn-danger"
        @click="handleDelete"
      >
        Destroy
      </button>
    </td>
  </tr>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'Category',
  props: {
    category: Object,
    handleDeleteCategory: Function,
    handleEditCategory: Function,
  },
  setup(props) {
    const edit = ref(false);
    const form = ref({
      code: props.category.code,
      description: props.category.description,
    });

    const toggleEdit = () => {
      edit.value = !edit.value;
    };

    const handleDelete = async () => {
      if (confirm('Are you sure?')) {
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        const response = await fetch(`/categories/${props.category.id}`, {
          method: 'DELETE',
          headers: {
            'X-CSRF-Token': csrfToken,
          },
        });

        if (response.ok) {
          props.handleDeleteCategory(props.category);
        }
      }
    };

    const handleEdit = async () => {
      const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
      const response = await fetch(`/categories/${props.category.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': csrfToken,
        },
        body: JSON.stringify({ category: form.value }),
      });

      if (response.ok) {
        const data = await response.json();
        props.handleEditCategory(props.category, data);
        edit.value = false;
      }
    };

    return {
      edit,
      form,
      toggleEdit,
      handleDelete,
      handleEdit,
    };
  },
};
</script>

// app/assets/javascripts/components/category.jsx
import React, { useState, useRef } from 'react';

const Category = ({ category, handleDeleteCategory, handleEditCategory }) => {
  const [edit, setEdit] = useState(false);
  const codeRef = useRef(null);
  const descriptionRef = useRef(null);

  const handleToggle = (e) => {
    e.preventDefault();
    setEdit(!edit);
  };

  const handleDelete = (e) => {
    if (confirm("Are you sure?")) {
      e.preventDefault();
      $.ajaxSetup({
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        }
      });
      $.ajax({
        method: 'DELETE',
        url: `/categories/${category.id}`,
        dataType: 'JSON',
        success: () => {
          handleDeleteCategory(category);
        }
      });
    }
  };

  const handleEdit = (e) => {
    e.preventDefault();
    const data = {
      code: codeRef.current.value,
      description: descriptionRef.current.value
    };
    $.ajaxSetup({
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      }
    });
    $.ajax({
      method: 'PUT',
      url: `/categories/${category.id}`,
      dataType: 'JSON',
      data: { category: data },
      success: (updatedCategory) => {
        setEdit(false);
        handleEditCategory(category, updatedCategory);
      }
    });
  };

  const categoryRow = () => (
    <tr>
      <td>
        <a href={`/categories/${category.id}`}>{category.code}</a>
      </td>
      <td>{category.description}</td>
      <td>
        <button className="btn btn-mini" onClick={handleToggle}>Edit</button>
        {' '}
        <button className="btn btn-mini btn-danger" onClick={handleDelete}>Destroy</button>
      </td>
    </tr>
  );

  const categoryForm = () => (
    <tr>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue={category.code}
          ref={codeRef}
        />
      </td>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue={category.description}
          ref={descriptionRef}
        />
      </td>
      <td>
        <button className="btn btn-mini btn-default" onClick={handleEdit}>Update</button>
        <button className="btn btn-mini btn-danger" onClick={handleToggle}>Cancel</button>
      </td>
    </tr>
  );

  return edit ? categoryForm() : categoryRow();
};

export default Category;
