// app/assets/javascripts/components/categories.jsx
import { html } from 'htm/react';
import React, { useState } from 'react';
import CategoryForm from './CategoryForm';
import Category from './Category';

const Categories = ({ data, page_header, form_data }) => {
  const [items, setItems] = useState(data || []);

  const addItem = (item) => {
    setItems((prevItems) => [...prevItems, item]);
  };

  const deleteItem = (item) => {
    setItems((prevItems) => prevItems.filter((i) => i !== item));
  };

  const updateItem = (item, updatedData) => {
    setItems((prevItems) =>
      prevItems.map((i) => (i === item ? updatedData : i))
    );
  };

  return html`
    <div className="categories">
      <h1 className="title">${page_header}</h1>
      ${CategoryForm({ handleNewCategory: addItem, form_data })}
      <hr />
      <table className="table table-striped">
        <thead>
          <tr>
            <th>Code</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          ${items.map((item) =>
            Category({
              key: item.id,
              category: item,
              handleDeleteCategory: deleteItem,
              handleEditCategory: updateItem,
              form_data
            })
          )}
        </tbody>
      </table>
    </div>
  `;
};

export default Categories;

// app/assets/javascripts/components/Categories.vue
<template>
  <div class="categories">
    <h1 class="title">{{ pageHeader }}</h1>
    <CategoryForm :handleNewCategory="addItem" :formData="formData" />
    <hr />
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Code</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <Category
          v-for="item in items"
          :key="item.id"
          :category="item"
          :handleDeleteCategory="deleteItem"
          :handleEditCategory="updateItem"
          :formData="formData"
        />
      </tbody>
    </table>
  </div>
</template>

<script>
import { ref } from 'vue';
import CategoryForm from './CategoryForm.vue';
import Category from './Category.vue';

export default {
  name: 'Categories',
  components: { CategoryForm, Category },
  props: {
    data: Array,
    pageHeader: String,
    formData: Object,
  },
  setup(props) {
    const items = ref(props.data);

    const addItem = (item) => {
      items.value.push(item);
    };

    const deleteItem = (item) => {
      const index = items.value.indexOf(item);
      if (index > -1) {
        items.value.splice(index, 1);
      }
    };

    const updateItem = (item, data) => {
      const index = items.value.indexOf(item);
      if (index > -1) {
        items.value.splice(index, 1, data);
      }
    };

    return {
      items,
      addItem,
      deleteItem,
      updateItem,
    };
  },
};
</script>
