// app/assets/javascripts/components/document_types.jsx
import { html } from 'htm/react';
import React, { useState } from 'react';
import DocumentTypeForm from './DocumentTypeForm';
import DocumentType from './DocumentType';

const DocumentTypes = ({ data, page_header, form_data }) => {
  const [documentTypes, setDocumentTypes] = useState(data || []);

  const addDocumentType = (documentType) => {
    setDocumentTypes((prevDocumentTypes) => [...prevDocumentTypes, documentType]);
  };

  const deleteDocumentType = (documentType) => {
    setDocumentTypes((prevDocumentTypes) =>
      prevDocumentTypes.filter((dt) => dt !== documentType)
    );
  };

  const updateDocumentType = (documentType, updatedData) => {
    setDocumentTypes((prevDocumentTypes) =>
      prevDocumentTypes.map((dt) => (dt === documentType ? updatedData : dt))
    );
  };

  return html`
    <div className="document-types">
      <h1 className="title">${page_header}</h1>
      ${DocumentTypeForm({ handleNewDocumentType: addDocumentType, form_data })}
      <hr />
      <table className="table table-striped">
        <thead>
          <tr>
            <th>Description</th>
            <th>Account Type</th>
            <th>Stock Type</th>
            <th>Stock</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          ${documentTypes.map((documentType) =>
            DocumentType({
              key: documentType.id,
              document_type: documentType,
              handleDeleteDocumentType: deleteDocumentType,
              handleEditDocumentType: updateDocumentType,
              form_data
            })
          )}
        </tbody>
      </table>
    </div>
  `;
};

export default DocumentTypes;

// app/assets/javascripts/components/DocumentTypes.vue
<template>
  <div class="document-types">
    <h1 class="title">{{ pageHeader }}</h1>
    <DocumentTypeForm :handleNewDocumentType="addDocumentType" :formData="formData" />
    <hr />
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Description</th>
          <th>Account Type</th>
          <th>Stock Type</th>
          <th>Stock</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <DocumentType
          v-for="documentType in documentTypes"
          :key="documentType.id"
          :documentType="documentType"
          :handleDeleteDocumentType="deleteDocumentType"
          :handleEditDocumentType="updateDocumentType"
          :formData="formData"
        />
      </tbody>
    </table>
  </div>
</template>

<script>
import { ref } from 'vue';
import DocumentTypeForm from './DocumentTypeForm.vue';
import DocumentType from './DocumentType.vue';

export default {
  name: 'DocumentTypes',
  components: { DocumentTypeForm, DocumentType },
  props: {
    data: Array,
    pageHeader: String,
    formData: Object,
  },
  setup(props) {
    const documentTypes = ref(props.data);

    const addDocumentType = (documentType) => {
      documentTypes.value.push(documentType);
    };

    const deleteDocumentType = (documentType) => {
      const index = documentTypes.value.indexOf(documentType);
      if (index > -1) {
        documentTypes.value.splice(index, 1);
      }
    };

    const updateDocumentType = (documentType, data) => {
      const index = documentTypes.value.indexOf(documentType);
      if (index > -1) {
        documentTypes.value.splice(index, 1, data);
      }
    };

    return {
      documentTypes,
      addDocumentType,
      deleteDocumentType,
      updateDocumentType,
    };
  },
};
</script>
