// app/assets/javascripts/components/PaymentTypes.vue
<template>
  <div class="payment_types">
    <h1 class="title">{{ pageHeader }}</h1>
    <PaymentTypeForm :handleNewPaymentType="addItem" :formData="formData" />
    <hr />
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Code</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <PaymentType
          v-for="item in items"
          :key="item.id"
          :paymentType="item"
          :handleDeletePaymentType="deleteItem"
          :handleEditPaymentType="updateItem"
          :formData="formData"
        />
      </tbody>
    </table>
  </div>
</template>

<script>
import { ref } from 'vue';
import PaymentTypeForm from './PaymentTypeForm.vue';
import PaymentType from './PaymentType.vue';

export default {
  name: 'PaymentTypes',
  components: { PaymentTypeForm, PaymentType },
  props: {
    data: Array,
    pageHeader: String,
    formData: Object,
  },
  setup(props) {
    const items = ref(props.data);

    const addItem = (item) => {
      items.value.push(item);
    };

    const deleteItem = (item) => {
      const index = items.value.indexOf(item);
      if (index > -1) {
        items.value.splice(index, 1);
      }
    };

    const updateItem = (item, data) => {
      const index = items.value.indexOf(item);
      if (index > -1) {
        items.value.splice(index, 1, data);
      }
    };

    return {
      items,
      addItem,
      deleteItem,
      updateItem,
    };
  },
};
</script>

// app/assets/javascripts/components/payment_types.jsx
import { html } from 'htm/react';
import React, { useState } from 'react';
import PaymentTypeForm from './PaymentTypeForm';
import PaymentType from './PaymentType';

const PaymentTypes = ({ data, page_header, form_data }) => {
  const [items, setItems] = useState(data || []);

  const addItem = (item) => {
    setItems((prevItems) => [...prevItems, item]);
  };

  const deleteItem = (item) => {
    setItems((prevItems) => prevItems.filter((i) => i !== item));
  };

  const updateItem = (item, updatedData) => {
    setItems((prevItems) =>
      prevItems.map((i) => (i === item ? updatedData : i))
    );
  };

  return html`
    <div className="payment_types">
      <h1 className="title">${page_header}</h1>
      ${PaymentTypeForm({ handleNewPaymentType: addItem, form_data })}
      <hr />
      <table className="table table-striped">
        <thead>
          <tr>
            <th>Code</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          ${items.map((item) =>
            PaymentType({
              key: item.id,
              payment_type: item,
              handleDeletePaymentType: deleteItem,
              handleEditPaymentType: updateItem,
              form_data
            })
          )}
        </tbody>
      </table>
    </div>
  `;
};

export default PaymentTypes;
