// app/assets/javascripts/components/payment_type.jsx
import React, { useState, useRef } from 'react';

const PaymentType = ({ payment_type, handleDeletePaymentType, handleEditPaymentType }) => {
  const [edit, setEdit] = useState(false);
  const codeRef = useRef(null);
  const descriptionRef = useRef(null);

  const handleToggle = (e) => {
    e.preventDefault();
    setEdit(!edit);
  };

  const handleDelete = (e) => {
    if (confirm("Are you sure?")) {
      e.preventDefault();
      $.ajaxSetup({
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        }
      });
      $.ajax({
        method: 'DELETE',
        url: `/payment_types/${payment_type.id}`,
        dataType: 'JSON',
        success: () => {
          handleDeletePaymentType(payment_type);
        }
      });
    }
  };

  const handleEdit = (e) => {
    e.preventDefault();
    const data = {
      code: codeRef.current.value,
      description: descriptionRef.current.value
    };
    $.ajaxSetup({
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      }
    });
    $.ajax({
      method: 'PUT',
      url: `/payment_types/${payment_type.id}`,
      dataType: 'JSON',
      data: { payment_type: data },
      success: (updatedPaymentType) => {
        setEdit(false);
        handleEditPaymentType(payment_type, updatedPaymentType);
      }
    });
  };

  const paymentTypeRow = () => (
    <tr>
      <td>
        <a href={`/payment_types/${payment_type.id}`}>{payment_type.code}</a>
      </td>
      <td>{payment_type.description}</td>
      <td>
        <button className="btn btn-mini" onClick={handleToggle}>Edit</button>
        {' '}
        <button className="btn btn-mini btn-danger" onClick={handleDelete}>Destroy</button>
      </td>
    </tr>
  );

  const paymentTypeForm = () => (
    <tr>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue={payment_type.code}
          ref={codeRef}
        />
      </td>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue={payment_type.description}
          ref={descriptionRef}
        />
      </td>
      <td>
        <button className="btn btn-mini btn-default" onClick={handleEdit}>Update</button>
        <button className="btn btn-mini btn-danger" onClick={handleToggle}>Cancel</button>
      </td>
    </tr>
  );

  return edit ? paymentTypeForm() : paymentTypeRow();
};

export default PaymentType;

// app/assets/javascripts/components/PaymentType.vue
<template>
  <tr v-if="edit">
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.code"
      />
    </td>
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.description"
      />
    </td>
    <td>
      <button
        class="btn btn-mini btn-default"
        @click="handleEdit"
      >
        Update
      </button>
      <button
        class="btn btn-mini btn-danger"
        @click="toggleEdit"
      >
        Cancel
      </button>
    </td>
  </tr>
  <tr v-else>
    <td>
      <a :href="`/payment_types/${paymentType.id}`">{{ paymentType.code }}</a>
    </td>
    <td>{{ paymentType.description }}</td>
    <td>
      <button
        class="btn btn-mini"
        @click="toggleEdit"
      >
        Edit
      </button>
      <button
        class="btn btn-mini btn-danger"
        @click="handleDelete"
      >
        Destroy
      </button>
    </td>
  </tr>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'PaymentType',
  props: {
    paymentType: Object,
    handleDeletePaymentType: Function,
    handleEditPaymentType: Function,
  },
  setup(props) {
    const edit = ref(false);
    const form = ref({
      code: props.paymentType.code,
      description: props.paymentType.description,
    });

    const toggleEdit = () => {
      edit.value = !edit.value;
    };

    const handleDelete = async () => {
      if (confirm('Are you sure?')) {
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        const response = await fetch(`/payment_types/${props.paymentType.id}`, {
          method: 'DELETE',
          headers: {
            'X-CSRF-Token': csrfToken,
          },
        });

        if (response.ok) {
          props.handleDeletePaymentType(props.paymentType);
        }
      }
    };

    const handleEdit = async () => {
      const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
      const response = await fetch(`/payment_types/${props.paymentType.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': csrfToken,
        },
        body: JSON.stringify({ payment_type: form.value }),
      });

      if (response.ok) {
        const data = await response.json();
        props.handleEditPaymentType(props.paymentType, data);
        edit.value = false;
      }
    };

    return {
      edit,
      form,
      toggleEdit,
      handleDelete,
      handleEdit,
    };
  },
};
</script>
