// app/assets/javascripts/components/WarehouseForm.vue
<template>
  <form class="form-inline" @submit.prevent="handleSubmit">
    <input
      type="text"
      placeholder="Code"
      name="code"
      v-model="form.code"
    />
    <input
      type="text"
      placeholder="Name"
      name="name"
      v-model="form.name"
    />
    <input
      type="text"
      placeholder="City"
      name="city"
      v-model="form.city"
    />
    <button
      type="submit"
      class="btn btn-primary"
      :disabled="!isValid"
    >
      Create
    </button>
  </form>
</template>

<script>
import { ref, computed } from 'vue';

export default {
  name: 'WarehouseForm',
  props: {
    handleNewWarehouse: Function,
  },
  setup(props) {
    const form = ref({
      code: '',
      name: '',
      city: '',
    });

    const handleSubmit = async () => {
      const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
      const response = await fetch('/warehouses', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': csrfToken,
        },
        body: JSON.stringify({ warehouse: form.value }),
      });

      if (response.ok) {
        const data = await response.json();
        props.handleNewWarehouse(data);
        form.value = { code: '', name: '', city: '' };
      }
    };

    const isValid = computed(() => form.value.code && form.value.name);

    return {
      form,
      handleSubmit,
      isValid,
    };
  },
};
</script>

// app/assets/javascripts/components/warehouse_form.jsx
import React, { useState } from 'react';

const WarehouseForm = ({ handleNewWarehouse }) => {
  const [formState, setFormState] = useState({
    code: '',
    name: '',
    city: ''
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    $.ajaxSetup({
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      }
    });
    $.post('/warehouses', { warehouse: formState }, (data) => {
      handleNewWarehouse(data);
      setFormState({ code: '', name: '', city: '' });
    }, 'JSON');
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormState((prevState) => ({ ...prevState, [name]: value }));
  };

  const isValid = () => formState.code && formState.name;

  return (
    <form className="form-inline" onSubmit={handleSubmit}>
      <input
        type="text"
        placeholder="Code"
        name="code"
        value={formState.code}
        onChange={handleChange}
      />
      <input
        type="text"
        placeholder="Name"
        name="name"
        value={formState.name}
        onChange={handleChange}
      />
      <input
        type="text"
        placeholder="City"
        name="city"
        value={formState.city}
        onChange={handleChange}
      />
      <button
        type="submit"
        className="btn btn-primary"
        disabled={!isValid()}
      >
        Create
      </button>
    </form>
  );
};

export default WarehouseForm;
