// app/assets/javascripts/components/warehouses.jsx
import { html } from 'htm/react';
import React, { useState } from 'react';
import WarehouseForm from './WarehouseForm';
import Warehouse from './Warehouse';

const Warehouses = ({ data, page_header, form_data }) => {
  const [items, setItems] = useState(data || []);

  const addItem = (item) => {
    setItems((prevItems) => [...prevItems, item]);
  };

  const deleteItem = (item) => {
    setItems((prevItems) => prevItems.filter((i) => i !== item));
  };

  const updateItem = (item, updatedData) => {
    setItems((prevItems) =>
      prevItems.map((i) => (i === item ? updatedData : i))
    );
  };

  return html`
    <div className="warehouses">
      <h1 className="title">${page_header}</h1>
      ${WarehouseForm({ handleNewWarehouse: addItem, form_data })}
      <hr />
      <table className="table table-striped">
        <thead>
          <tr>
            <th>Code</th>
            <th>Name</th>
            <th>City</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          ${items.map((item) =>
            Warehouse({
              key: item.id,
              warehouse: item,
              handleDeleteWarehouse: deleteItem,
              handleEditWarehouse: updateItem,
              form_data
            })
          )}
        </tbody>
      </table>
    </div>
  `;
};

export default Warehouses;

// app/assets/javascripts/components/Warehouses.vue
<template>
  <div class="warehouses">
    <h1 class="title">{{ pageHeader }}</h1>
    <WarehouseForm :handleNewWarehouse="addItem" :formData="formData" />
    <hr />
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Code</th>
          <th>Name</th>
          <th>City</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <Warehouse
          v-for="item in items"
          :key="item.id"
          :warehouse="item"
          :handleDeleteWarehouse="deleteItem"
          :handleEditWarehouse="updateItem"
          :formData="formData"
        />
      </tbody>
    </table>
  </div>
</template>

<script>
import { ref } from 'vue';
import WarehouseForm from './WarehouseForm.vue';
import Warehouse from './Warehouse.vue';

export default {
  name: 'Warehouses',
  components: { WarehouseForm, Warehouse },
  props: {
    data: Array,
    pageHeader: String,
    formData: Object,
  },
  setup(props) {
    const items = ref(props.data);

    const addItem = (item) => {
      items.value.push(item);
    };

    const deleteItem = (item) => {
      const index = items.value.indexOf(item);
      if (index > -1) {
        items.value.splice(index, 1);
      }
    };

    const updateItem = (item, data) => {
      const index = items.value.indexOf(item);
      if (index > -1) {
        items.value.splice(index, 1, data);
      }
    };

    return {
      items,
      addItem,
      deleteItem,
      updateItem,
    };
  },
};
</script>
