// app/assets/javascripts/components/Warehouse.vue
<template>
  <tr v-if="edit">
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.code"
      />
    </td>
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.name"
      />
    </td>
    <td>
      <input
        class="form-control"
        type="text"
        v-model="form.city"
      />
    </td>
    <td>
      <button
        class="btn btn-mini btn-default"
        @click="handleEdit"
      >
        Update
      </button>
      <button
        class="btn btn-mini btn-danger"
        @click="toggleEdit"
      >
        Cancel
      </button>
    </td>
  </tr>
  <tr v-else>
    <td>
      <a :href="`/warehouses/${warehouse.id}`">{{ warehouse.code }}</a>
    </td>
    <td>{{ warehouse.name }}</td>
    <td>{{ warehouse.city }}</td>
    <td>
      <button
        class="btn btn-mini"
        @click="toggleEdit"
      >
        Edit
      </button>
      <button
        class="btn btn-mini btn-danger"
        @click="handleDelete"
      >
        Destroy
      </button>
    </td>
  </tr>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'Warehouse',
  props: {
    warehouse: Object,
    handleDeleteWarehouse: Function,
    handleEditWarehouse: Function,
  },
  setup(props) {
    const edit = ref(false);
    const form = ref({
      code: props.warehouse.code,
      name: props.warehouse.name,
      city: props.warehouse.city,
    });

    const toggleEdit = () => {
      edit.value = !edit.value;
    };

    const handleDelete = async () => {
      if (confirm('Are you sure?')) {
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        const response = await fetch(`/warehouses/${props.warehouse.id}`, {
          method: 'DELETE',
          headers: {
            'X-CSRF-Token': csrfToken,
          },
        });

        if (response.ok) {
          props.handleDeleteWarehouse(props.warehouse);
        }
      }
    };

    const handleEdit = async () => {
      const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
      const response = await fetch(`/warehouses/${props.warehouse.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': csrfToken,
        },
        body: JSON.stringify({ warehouse: form.value }),
      });

      if (response.ok) {
        const data = await response.json();
        props.handleEditWarehouse(props.warehouse, data);
        edit.value = false;
      }
    };

    return {
      edit,
      form,
      toggleEdit,
      handleDelete,
      handleEdit,
    };
  },
};
</script>

// app/assets/javascripts/components/warehouse.jsx
import React, { useState, useRef } from 'react';

const Warehouse = ({ warehouse, handleDeleteWarehouse, handleEditWarehouse }) => {
  const [edit, setEdit] = useState(false);
  const codeRef = useRef(null);
  const nameRef = useRef(null);
  const cityRef = useRef(null);

  const handleToggle = (e) => {
    e.preventDefault();
    setEdit(!edit);
  };

  const handleDelete = (e) => {
    if (confirm("Are you sure?")) {
      e.preventDefault();
      $.ajaxSetup({
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        }
      });
      $.ajax({
        method: 'DELETE',
        url: `/warehouses/${warehouse.id}`,
        dataType: 'JSON',
        success: () => {
          handleDeleteWarehouse(warehouse);
        }
      });
    }
  };

  const handleEdit = (e) => {
    e.preventDefault();
    const data = {
      code: codeRef.current.value,
      name: nameRef.current.value,
      city: cityRef.current.value
    };
    $.ajaxSetup({
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      }
    });
    $.ajax({
      method: 'PUT',
      url: `/warehouses/${warehouse.id}`,
      dataType: 'JSON',
      data: { warehouse: data },
      success: (updatedWarehouse) => {
        setEdit(false);
        handleEditWarehouse(warehouse, updatedWarehouse);
      }
    });
  };

  const warehouseRow = () => (
    <tr>
      <td>
        <a href={`/warehouses/${warehouse.id}`}>{warehouse.code}</a>
      </td>
      <td>{warehouse.name}</td>
      <td>{warehouse.city}</td>
      <td>
        <button className="btn btn-mini" onClick={handleToggle}>Edit</button>
        {' '}
        <button className="btn btn-mini btn-danger" onClick={handleDelete}>Destroy</button>
      </td>
    </tr>
  );

  const warehouseForm = () => (
    <tr>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue={warehouse.code}
          ref={codeRef}
        />
      </td>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue={warehouse.name}
          ref={nameRef}
        />
      </td>
      <td>
        <input
          className="form-control"
          type="text"
          defaultValue={warehouse.city}
          ref={cityRef}
        />
      </td>
      <td>
        <button className="btn btn-mini btn-default" onClick={handleEdit}>Update</button>
        <button className="btn btn-mini btn-danger" onClick={handleToggle}>Cancel</button>
      </td>
    </tr>
  );

  return edit ? warehouseForm() : warehouseRow();
};

export default Warehouse;
